### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by DarkxDev** [dennis-every/dd_eats#35]
**Great work on your project so far! 🥳**
### Highlights:
- Clean code
- Well organized
- Follows best practices

Suggestions:
- Please consider that currently the "like" button can be clicked infinitely.
- We suggest adjusting the font size of the popup ratio so it is easier to read.

**Comment by dennis-every** [comment]
Great, tks! Issues addressed in this [PR](https://github.com/dennis-every/dd_eats/pull/37)
